name: package-manager-publish
on:
  push:
    branches: [main]

jobs:
  package-manager-publish:
    name: package-manager-publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish to Package Manager
        uses: jvroberts/actions/package-manager-publish@package-manager-publish
        with:
          url: ${{ secrets.PPM_URL }}
          api-key: ${{ secrets.PPM_API_TOKEN }}
          r-version: 4.2.0
          distro: jammy
          source: local
