name: package-manager-publish-r
on:
  push:
    branches: [main]

jobs:
  package-manager-publish-r:
    name: package-manager-publish-r
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish to Package Manager
        uses: jvroberts/actions/package-manager-publish-r@package-manager-publish
        with:
          url: ${{ secrets.PPM_URL }}
          api-token: ${{ secrets.PPM_API_TOKEN }}
          r-version: release
          distro: jammy
          source: local
